language: objective-c
osx_image: xcode83
rvm:
- 2.1.2
install:
- ./Scripts/install.sh
script:
- ./Scripts/testrunner.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c5b8011de8371ab421cf
      - https://webhooks.gitter.im/e/397c5ae53eee6ad85baa
    on_success: change
    on_failure: always
    on_start: never